### ISSUE TITLE
Build Documentation is Incorrect

### ISSUE THREAD

**Issue by akiraw** [emccode/polly#111]
Documentation states that a simple build of poly requires only a make. In practice this alone doesn't work- it requires a make clean; make deps; make

**Comment by akutz** [comment]
Hi @akiraw,

I'm going to close this issue. The reason being is that you do not need to open an issue if you're also able to submit a PR. We prefer the latter approach when possible since a PR also acts as the issue. Unless that is you do not intend to file a PR? If you don't, I'll reopen this issue for tracking.
